add description for catoptioncombo viewType column headers
EyeSeeTea/d2-autogen-forms pull request #9
Opened 2024-01-11 15:03 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8693fnxz5

### :memo: Implementation

### :art: Screenshots
<img width="1262" alt="Screenshot 2024-01-11 at 15 43 02" src="https://github.com/EyeSeeTea/d2-autogen-forms/assets/37223065/2d30b092-33f5-496b-96fa-dbeafe05f9ca">

### :fire: Notes to the tester
Datastore config:
```
"columnsDescriptions": {
    "Combined": "Only data that cannot be disaggregated into separate health sectors",
    "Community": "Only data from the community health workers",
    "Private": "Only data from the private health facilities",
    "Public": {
      "code": "PUBLIC"
    }
  }
```
where `Combined`, `Community`, `Private`, `Public` are the column names and `{code: "PUBLIC"}` is referencing a constant code. 

`REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238/
`

2024-01-12 09:54 UTC, MiquelAdell approved these changes
It works for me. I created a test with another constant in 
https://dev.eyeseetea.com/who-dev-238/dhis-web-datastore/index.html#/edit/d2-autogen-forms/MAL-WMR
@eperedo if you have a moment to code review that.

Thank you both

2024-01-12 22:15 UTC, eperedo requested changes
thanks @deeonwuli for the code, functionality looks great, but I think using the code of a cat. combination is only going to work for this particular viewType and not in grids. For example in this section: `Completeness of outpatient reporting 2022`
![image](https://github.com/EyeSeeTea/d2-autogen-forms/assets/461124/816abfee-43ab-4557-a3a8-cabb378bac2f)

In this case **Public, Private and community based** are just columns we create from the dataelement's formName. 

Maybe as a more generic implementation we can use the column name as an identifier instead of the combination code. 

what do you think? @deeonwuli @MiquelAdell

2024-01-15 07:10 UTC, MiquelAdell commented on src/domain/common/entities/DataForm.ts
> +    categoryDescriptions: CategoryDescription;
the change of label is ok by me

2024-01-15 09:51 UTC, deeonwuli commented on src/webapp/reports/autogenerated-forms/GridWithCatOptionCombos.tsx
> +        fontWeight: "bold" as const,
the cast isn't absolutely necessary, i'll take it out.

2024-01-16 00:32 UTC, eperedo approved these changes
Everything looks good, thanks @deeonwuli.

2024-01-16 14:57 UTC, merged